/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author LGC
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class crudPanel extends javax.swing.JPanel {

    /**
     * Creates new form crudPanel
     */
    public crudPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setToolTipText("");

        jLabel1.setText("Enregistremant de l'etudiant");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOM", "NOTE"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel2.setText("NOM");

        jLabel3.setText("NOTE");

        jScrollPane3.setViewportView(jTextPane1);

        jScrollPane4.setViewportView(jTextPane2);

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("ENVOYER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("SUPPRIMER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 102));
        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setText("EDITER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(549, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("LOL");

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     int row =ID.getSelectedRow();
       if (row == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un étudiant !");
            return;
        }
    int id = (int) ID.getValueAt(row, 0);
       int confirm = JOptionPane.showConfirmDialog(this,
         "Voulez-vous vraiment supprimer cet étudiant ?", "Confirmation",
           JOptionPane.YES_NO_OPTION);
       if (confirm == JOptionPane.YES_OPTION) {
           try (Connection con = Connexion.getConnection()) {
           String sql = "DELETE FROM etudiant WHERE id = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, id);
            ps.executeUpdate();
            chargerEtudiantsEtActiverSelection();
            JOptionPane.showMessageDialog(this, "Étudiant supprimé !");} catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur lors de la suppression !");
        }
    }
}
       


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int row = ID.getSelectedRow();
        if (row == -1) {
           JOptionPane.showMessageDialog(this, "Veuillez sélectionner un étudiant !");
            return;
        }
           int id = (int) ID.getValueAt(row, 0);
              String nom = jTextField1.getText().trim();
        
          double note;
try {
note = Double.parseDouble(jTextField2.getText().trim());
} catch (NumberFormatException ex) {
JOptionPane.showMessageDialog(this, "La note doit être un nombre !");
return;
}
try (Connection con = Connexion.getConnection()) {
String sql = "UPDATE etudiant SET nom = ?, note = ? WHERE id = ?";
PreparedStatement ps = con.prepareStatement(sql);
ps.setString(1, nom);
ps.setDouble(2, note);ps.setInt(3, id);
ps.executeUpdate();
chargerEtudiantsEtActiverSelection();
JOptionPane.showMessageDialog(this, "Étudiant modifié !");
jTextField1.setText("");
jTextField2.setText("");
} catch (Exception e) {
e.printStackTrace();
JOptionPane.showMessageDialog(this, "Erreur lors de la modification !");
}
}
        
        private void chargerEtudiantsEtActiverSelection() {
DefaultTableModel model = (DefaultTableModel) ID.getModel();
model.setRowCount(0);
try (Connection con = Connexion.getConnection()) {
Statement st = con.createStatement();
ResultSet rs = st.executeQuery("SELECT * FROM etudiant");
while (rs.next()) {
model.addRow(new Object[]{
rs.getInt("id"),
rs.getString("nom"),
rs.getDouble("note")
});
}
} catch (Exception e) {
e.printStackTrace();}
// Ajoute le listener une seule fois
if (ID.getMouseListeners().length == 1) {
ID.addMouseListener(new java.awt.event.MouseAdapter() {
@Override
public void mouseClicked(java.awt.event.MouseEvent evt) {
int row = ID.getSelectedRow();
if (row != -1) {
String nom = (String) ID.getValueAt(row, 1);
double note = (double) ID.getValueAt(row, 2);
jTextField1.setText(nom);
jTextField2.setText(String.valueOf(note));
}
}
});
}
}


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nom = jTextField1.getText().trim();
if (nom.isEmpty() || jTextField2.getText().trim().isEmpty()) {
JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !");
return;
}
double note;
try {
note = Double.parseDouble(jTextField2.getText().trim());
} catch (NumberFormatException ex) {
JOptionPane.showMessageDialog(this, "La note doit être un nombre !");
return;
}
try (Connection con = Connexion.getConnection()) {
String sql = "INSERT INTO etudiant(nom, note) VALUES (?, ?)";
PreparedStatement ps = con.prepareStatement(sql);
ps.setString(1, nom);
ps.setDouble(2, note);
ps.executeUpdate();
chargerEtudiantsEtActiverSelection();
JOptionPane.showMessageDialog(this, "Étudiant ajouté avec succès !");jTextField1.setText("");
jTextField2.setText("");
} catch (Exception e) {
e.printStackTrace();
JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout !");
}
}

    }//GEN-LAST:event_jButton1ActionPerformed
    
       
                  
    
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
